# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: 'default'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '13.x'
  displayName: 'Install Node.js'

- script: npm install -g @angular/cli
  displayName: 'Install NPM'
    
- script: npm install
  displayName: 'Install NPM Packages'

- script: ng build --prod
  displayName: 'Build App'

- task: CopyFiles@2
  inputs:
    Contents: '$(Build.Repository.LocalPath)/dist/**' ## update to match what you want to copy
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'angularDrop'
    publishLocation: 'Container'