import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { Job } from '../models/Job';
import { Applicant } from '../models/Applicant';

@Injectable({
  providedIn: 'root'
})
export class ResumeService {

  constructor() { }

  private constApplicant: Applicant = {
    firstName: 'Brian',
    lastName: 'Arnold',
    middleNameOrInitial: 'C.',
    address1: '3501 Calumet Dr',
    address2: null,
    city: 'Orlando',
    state: 'FL',
    postalCode: '35810',
    phoneNumber: '256-652-6754',
    email: 'brian.ch.arnold@gmail.com',
    skillAreas: [
      {
        desc: 'Frontend',
        skills: [
          {
            desc: 'Angular',
          },
          {
            desc: 'Bootstrap'
          },
          {
            desc: 'RxJS'
          }
        ]
      },
      {
        desc: 'Backend',
        skills: [
          {
            desc: 'C#',
          },
          {
            desc: 'REST'
          },
          {
            desc: 'Entity Framework'
          }
        ]
      },
      {
        desc: 'Database',
        skills: [
          {
            desc: 'Oracle 18c',
          },
          {
            desc: 'Microsoft SQL Server'
          },
          {
            desc: 'Cosmos DB'
          }
        ]
      },
      {
        desc: 'Cloud',
        skills: [
          {
            desc: 'Azure Functions',
          },
          {
            desc: 'Azure CDN'
          },
          {
            desc: 'Azure DevOps'
          }
        ]
      }
    ]
  };

  private constJobs: Job[] = [
    {
      company: 'Red Lobster LLC',
      title: 'Senior Systems Engineer',
      location: 'Orlando, FL',
      startDate: 'May 2018',
      endDate: 'Current',
      achievements: [
        {
          desc: 'Architected and developed multitier application for Azure deployment',
          details: 'Legacy application utilized \
          ASP.NET 2.0 WebForms technology with a Lightspeed ORM repository front end for Oracle 11g. \
          The replacement application utilized Angular 7 (later upgraded to Angular 8 and then 9) with Bootstrap styles, \
          REST APIs provided by ASP.NET MVC API Controllers, and Entity Framework 6.1, later upgraded to Entity \
          Framework 2.1.',
          skills: [
            {
              desc: 'Database agnostic Data Context implemented with EF Core 2.1',
              details: 'Originally written in Entity Framework 6.1, however the interface was \
              later re-implemented in Entity Framework Core 2.1 when Oracle released their Entity Framework Provider \
              for Core.'
            },
            {
              desc: 'Microservice-compatible Business Logic System',
              details: 'This ASP.NET MVC WebAPI tier was written with the ability to be optionally deployed in Azure Functions. \
              Each WebAPI method defined also had a Azure Function method defined that will be deployed to Azure Functions when the \
              application is deployed using Azure Functions.'
            },
            { desc: 'Dynamic Angular 9 site with context dependent display',
              details: 'The front end was originally written with Angular 7, but upgraded in place to 8 during development, and then later \
              to 9 after initial deployment. While new features such as Ivy were unfortunately not able to be integrated into the site, \
              upgrades were still regularly to ensure that any deprecated technology in use was identified and updated.'
            }
          ]
        },
        {
          desc: 'Created recursion serialization system for TypeScript',
          details: 'One of the major issues encountered in serializing complex relational data models is that \
          referential loops can often result. In order to handle this eventuality, Newtonsoft Json.NET was configured to \
          preserve object references. However, no acceptable effective technology was found to handle the same reference \
          in TypeScript. To this end, any objects deserialized on the client were passed though a custom reference \
          rebuilder that used the object references from Newtonsoft to reconstruct the same object graph that was \
          present on the server before serialization. A related serializer was written to handle the process in reverse \
          before posting object graphs back to the server.'
        },
        { desc: 'Replaced flat file intra-system communication endpoints with modern APIs',
          details: 'All previous supply chain systems utilized CSV export and import for communication with other \
          systems. Knowing that further modernization of other systems would be limited to the capabilities of this \
          system, each CSV import or export was reimplemented with a modern REST API, and the CSVs were processed or generated by an \
          application that would read the data and POST the data to the REST API, or GET the data from the REST API and write the CSV \
          This ensured that older systems would continue to operate as expected with no modifications necessary, while newer applications \
          could utilize REST for data transfer. Additionally, high throughput endpoints were also implemented with WebSockets.'
        },
        {
          desc: 'Configured DevOps CI/CD pipelines for separate tier deployment',
          details: 'In order to ensure regular and fault-resistent deployments of the application, Build and Release pipelines \
          were implemented in Azure DevOps. Pull Requests were gated to require successful builds, successful deployment to a QA \
          environment, and successful end-to-end and unit testing for each request. After all checks were completed, manual approval \
          was required before final deployment to all production servers was completed.'
        },
        { desc: 'Utilized CI/CD pipelines to deploy bug fixes same-day',
          details: 'Due to the nature of the application and the high variability of business logic in place, the application was \
          written to stratify business rules based on workflow, product properties, and supplier information. As changes \
          to rules were handed down, I was able to quickly modify the business rules in the ruleset file by quickly navigating \
          to the relevant section and entering the logic in the relevant section. As the vast majority of the application was present \
          in this one aspect, this architecture, when combined with the DevOps pipelines and automated testing, allowed significant \
          changes to the application to be tested and deployed very quickly.'
        },
        {
          desc: 'Reduced known regression occurrence to zero',
          details: 'Because of the stratified nature of the rule definitions, rule changes were not prone to regressions.'
        },
        { desc: 'Upgraded frontend from Angular 7 to Angular 9 during development'},
        { desc: 'Upgraded backend from EF 6.1 to EF Core 2.1' }
      ],
      skills: [
        { desc: 'Angular 7/8/9' },
        { desc: 'Bootstrap 4.x' },
        { desc: '.NET Core 2.x' },
        { desc: 'Oracle 18c' },
        { desc: 'TypeScript 3.7' },
        { desc: 'Azure Functions' },
        { desc: 'Azure SQL ' },
        { desc: 'Kubernetes' },
        { desc: 'CDN' },
        { desc: 'Azure DevOps',
          skills: [
            { desc: 'CI/CD' },
            { desc: 'Pull Requests' }
          ]
        }
      ]
    },
    {
      company: 'Acme AtronOmatic LLC',
      title: 'Senior Software Engineer',
      location: 'Orlando, FL',
      startDate: 'Aug 2014',
      endDate: 'Apr 2018',
      achievements: [
        { desc: 'Designed replacement message processing architecture' },
        { desc: 'Updated ASMX webservices to WebAPI' },
        { desc: 'Created a CosmosDB persisted flight status in-memory cache' },
        { desc: 'Managed network architecture for hybrid datacenter and cloud environment' },
        { desc: 'Developed server management applications in WPF' }
      ],
      skills: [
        { desc: 'C#' },
        { desc: '.NET 4.6.1' },
        { desc: '.NET Core 1.1' },
        { desc: 'ASP.NET ' },
        { desc: 'Azure SQL' },
        { desc: 'Redis' },
        { desc: 'ASDI' },
        { desc: 'FLTD/SWIM' },
        { desc: 'SOAP' },
        { desc: 'REST' }
      ]
    },
    {
      company: 'Hunt Engineering Services, Inc.',
      title: 'Senior Software Engineer',
      location: 'Celebration, FL',
      startDate: 'Nov 2011',
      endDate: 'Aug 2014',
      achievements: [
        { desc: 'Collaboration with Software Development VP for architecture design' },
        { desc: 'Implemented and maintained visitor management systems for military bases' },
        { desc: 'Designed and implemented REST interfaces for existing SOAP APIs' },
        { desc: 'Designed and implemented SharePoint solution frontend for Oracle data' },
        { desc: 'Developed WPF application to interface biometric devices with website' }
      ],
      skills: [
        { desc: 'C#/VB.NET' },
        { desc: 'ASP.NET 4.5.1' },
        { desc: 'MVC 5' },
        { desc: 'EF 6' },
        { desc: 'SQL Server 2014 ' },
        { desc: 'SharePoint 2013' },
        { desc: 'Microsoft Azure' },
        { desc: 'WPF' },
        { desc: 'Oracle 11g' },
        { desc: 'PL/SQL' },
        { desc: 'Toad for Oracle' },
        { desc: 'Objective C' },
        { desc: 'Java' },
        { desc: 'SOAP' },
        { desc: 'REST' }
      ]
    },
    {
      company: 'GROWMARK, Inc.',
      title: 'Contractor',
      location: 'Bloomington, IL',
      startDate: 'Oct 2010',
      endDate: 'Oct 2011',
      achievements: [
        { desc: 'Implemented WebNow and ImageNow forms with XML, XSLT, and iScript' },
        { desc: 'Created image file processors to catalog file metadata on upload' }
      ],
      skills: [
        { desc: 'C#/F#' },
        { desc: 'ASP.NET 4.0' },
        { desc: 'SharePoint 2010' },
        { desc: 'HTML 5' },
        { desc: 'JQuery ' },
        { desc: 'XML' },
        { desc: 'XSLT' },
        { desc: 'XSD' }
      ]
    },
    {
      company: 'BAE Systems',
      title: 'Contractor',
      location: 'Huntsville',
      startDate: 'Dec 2007',
      endDate: 'Oct 2010',
      achievements: [
        { desc: 'Implemented SharePoint Features to provision SharePoint sites' },
        { desc: 'Created customized SharePoint workflows for Contract bidding' }
      ],
      skills: [
        { desc: 'C#'},
        { desc: 'SharePoint 2007'},
        { desc: 'ASP.NET 3.5'},
        { desc: 'HTML 4'},
        { desc: 'XML'},
        { desc: 'SOAP'}
      ]
    }
  ];

  public getResume(): Observable<Job[]> {
    return of(this.constJobs);
  }
  public getApplicant(): Observable<Applicant> {
    return of(this.constApplicant);
  }
}
