import { Job } from '../models/Job';

export const jobs: Job[] =
[
  {
    company: 'BNY Mellon',
    title: 'Contractor',
    location: 'Pittsburg, PA',
    startDate: 'April 2020',
    endDate: 'Current',
    achievements:[],
    skills: [
      {
        desc: 'Angular 9-11',
        skillTag: 'angular',
        url: 'https://golden-layout.com/',
        skills: [
          {
            desc: 'PrimeNG',
          },
          {
            desc: 'Shared Libs'
          },
          {
            desc: 'GoldenLayout',
            url: 'https://golden-layout.com/'
          },
        ]
      },
      {
        desc: 'Docker',
        skillTag: 'serverless'
      },
      {
        desc: 'SQL Server',
        skillTag: 'sqlserver'
      },
      {
        desc: '.NET Core 3.1',
        skillTag: 'dotnet'
      },
    ]
  },
  {
    company: 'Red Lobster LLC',
    title: 'Senior Systems Engineer',
    location: 'Orlando, FL',
    startDate: 'May 2018',
    endDate: 'March 2020',
    achievements: [
      {
        desc: 'Architected and developed multitier Azure application as Lead',
        details: [
          'Legacy application utilized ASP.NET 2.0 WebForms technology with a Lightspeed ORM repository front end for Oracle 11g.',
          'The replacement application utilized Angular 7 (later upgraded to Angular 8 and then 9) with Bootstrap styles.',
          'REST APIs were provided by ASP.NET MVC API Controllers.',
          'Entity Framework 6.1 was used initially, and later upgraded to Entity Framework 2.1.'
        ],
        skills: [
          {
            desc: 'Database agnostic Data Context implemented with EF Core 2.1',
            details: [
              'Originally written in Entity Framework 6.1 as Oracle had not yet released their Entity Framework Provider for Entity Framework Core.',
              'The interface was later re-implemented in Entity Framework Core 2.1 when Oracle released their Entity Framework Provider for Core.'
            ],
            skillTags: [
              'oracle',
              'dotnet',
              'entityframework'
            ]
          },
          {
            desc: 'Microservice-compatible Business Logic System',
            details: [
              'This ASP.NET MVC WebAPI tier was written with the ability to be optionally deployed in Azure Functions.',
              'Each WebAPI method defined also had a Azure Function method defined that will be deployed to Azure Functions when the application is deployed to Azure Serverless Architecture.'
            ],
            skillTags: [
              'dotnet',
              'rest',
              'serverless',
              'azure'
            ]
          },
          {
            desc: 'Dynamic Angular 9 site with context dependent display',
            details: [
              'The front end was originally written with Angular 7, but upgraded in place to 8 during development, and then later to 9 after initial deployment.',
              'While new features such as Ivy were unfortunately not able to be integrated into the site, upgrades were still regularly to ensure that any deprecated technology in use was identified and updated.'
            ],
            skillTags: [
              'angular',
              'typescript',
              'rest',
              'css'
            ]
          }
        ],
        skillTags: [
          'oracle',
          'dotnet',
          'entityframework',
          'rest',
          'serverless',
          'azure',
          'angular',
          'typescript',
          'css'
        ]
      },
      {
        desc: 'Created recursion serialization system for TypeScript',
        details: [
          'One of the major issues encountered in serializing complex relational data models is that referential loops can often result.',
          'In order to handle this eventuality, Newtonsoft Json.NET was configured to preserve object references. However, no acceptable effective technology was found to handle the same reference in TypeScript.',
          'To this end, any objects deserialized on the client were passed though a custom reference rebuilder that used the object references from Newtonsoft to reconstruct the same object graph that was present on the server before serialization.',
          'A related serializer was written to handle the process in reverse before posting object graphs back to the server.'
        ],
        skillTags:[
          'typescript',
          'rest'
        ]
      },
      {
        desc: 'Replaced flat file communication endpoints with modern APIs',
        details: [
          'All previous supply chain systems utilized CSV export and import for communication with other systems.',
          'In order to ensure that further modernization of other systems would not be limited to the capabilities of this the legacy system, each CSV import or export was reimplemented with a modern REST API, and the CSVs were processed or generated by an application that would read the data and POST the data to the REST API, or GET the data from the REST API and write the CSV.',
          'This ensured that older systems would continue to operate as expected with no modifications necessary, while newer applications could utilize REST for data transfer. Additionally, high throughput endpoints were also implemented with WebSockets.'
        ],
        skillTags:[
          'rest',
          'dotnet'
        ]
      },
      {
        desc: 'Configured DevOps CI/CD pipelines for separate tier deployment',
        details: [
          'In order to ensure regular and fault-resistent deployments of the application, Build and Release pipelines were implemented in Azure DevOps.',
          'Pull Requests were gated to require successful builds, successful deployment to a QA environment, and successful end-to-end and unit testing for each request.',
          'After all checks were completed, manual approval was required before final deployment to all production servers was completed.'
        ],
        skillTags:[
          'devops'
        ]
      },
      {
        desc: 'Utilized CI/CD pipelines to deploy bug fixes same-day',
        details: [
          'Due to the nature of the application and the high variability of business logic in place, the application was written to stratify business rules based on workflow, product properties, and supplier information.',
          'As changes to rules were handed down, the business rules were able to be quickly modified by navigating to the relevant section and modifying the logic.',
          'As the vast majority of application logic was present in this one aspect, this architecture allowed significant changes to the application to be tested and deployed very quickly.'
        ],
        skillTags:[
          'devops'
        ]
      },
      {
        desc: 'Reduced known regression occurrence to zero',
        skillTags:[]
      },
      {
        desc: 'Upgraded frontend from Angular 7 to Angular 9 during development',
        skillTags:[
          'angular',
          'typescript',
          'css'
        ]
      },
      {
        desc: 'Upgraded backend from EF 6.1 to EF Core 2.1',
        skillTags:[
          'entityframework',
          'dotnet',
          'oracle'
        ]
       }
    ],
    skills: [
      {
        desc: 'Angular 9'  ,
        skillTag: 'angular'
      },
      {
        desc: 'Bootstrap 4.x',
        skillTag: 'css'
      },
      {
        desc: '.NET Core 2.x'  ,
        skillTag: 'dotnet'
      },
      {
        desc: 'Oracle 18c'  ,
        skillTag: 'oracle'
      },
      {
        desc: 'TypeScript 3.7'  ,
        skillTag: 'typescript'
      },
      {
        desc: 'Azure Functions'  ,
        skillTag: 'serverless'
      },
      {
        desc: 'Azure SQL '  ,
        skillTag: 'sqlserver'
      },
      {
        desc: 'CDN'  ,
        skillTag: 'serverless'
      },
      {
        desc: 'Azure DevOps',
        skills: [
          {
            desc: 'CI/CD'
          },
          {
            desc: 'Pull Requests'
          }
        ] ,
        skillTag: 'devops'
      }
    ]
  },
  {
    company: 'Acme AtronOmatic LLC',
    title: 'Senior Software Engineer',
    location: 'Orlando, FL',
    startDate: 'Aug 2014',
    endDate: 'Apr 2018',
    achievements: [
      {
        desc: 'Designed replacement message processing architecture',
        skillTags:[
          'flight',
          'entityframework',
          'dotnet'
        ]
      },
      {
        desc: 'Updated ASMX web services to WebAPI',
        skillTags:[
          'flight',
          'rest'
        ]
      },
      {
        desc: 'Created a Cosmos DB persisted flight status in-memory cache',
        skillTags:[
          'nosql',
          'azure'
        ]
      },
      {
        desc: 'Managed network architecture for hybrid datacenter and cloud environment',
        skillTags:[
          'architecture'
        ]
      },
      {
        desc: 'Developed server management applications in WPF',
        skillTags:[
          'dotnet',
          'entityframework',
          'sqlserver'
        ]
      }
    ],
    skills: [
      {
        desc: 'C#' ,
        skillTag: 'dotnet'
      },
      {
        desc: '.NET 4.6.1' ,
        skillTag: 'dotnet'
      },
      {
        desc: 'ASP.NET ' ,
        skillTag: 'mvc'
      },
      {
        desc: 'Azure SQL' ,
        skillTag: 'sqlserver'
      },
      {
        desc: 'Redis' ,
        skillTag: 'nosql'
      },
      {
        desc: 'ASDI' ,
        skillTag: 'flight'
      },
      {
        desc: 'FLTD/SWIM' ,
        skillTag: 'flight'
      },
      {
        desc: 'REST' ,
        skillTag: 'rest'
      }
    ]
  },
  {
    company: 'Hunt Engineering Services, Inc.',
    title: 'Senior Software Engineer',
    location: 'Celebration, FL',
    startDate: 'Nov 2011',
    endDate: 'Aug 2014',
    achievements: [
      {
        desc: 'Collaboration with Software Development VP for architecture design',
        skillTags:[
          'architecture'
        ]
      },
      {
        desc: 'Implemented and maintained visitor management systems for military bases',
        skillTags:[
          'oracle'
        ]
      },
      {
        desc: 'Designed and implemented REST interfaces for existing SOAP APIs',
        skillTags:[
          'rest'
        ]
      },
      {
        desc: 'Designed and implemented SharePoint solution frontend for Oracle data',
        skillTags:[
          'sharepoint'
        ]
      },
      {
        desc: 'Developed WPF application to interface biometric devices with website',
        skillTags:[
          'dotnet'
        ]
      }
    ],
    skills: [
      {
        desc: 'C#/VB.NET' ,
        skillTag: 'dotnet'
      },
      {
        desc: 'ASP.NET 4.5.1' ,
        skillTag: 'dotnet'
      },
      {
        desc: 'MVC 5' ,
        skillTag: 'mvc'
      },
      {
        desc: 'EF 6' ,
        skillTag: 'entityframework'
      },
      {
        desc: 'SQL Server 2014 ' ,
        skillTag: 'sqlserver'
      },
      {
        desc: 'SharePoint 2013' ,
        skillTag: 'sharepoint'
      },
      {
        desc: 'Microsoft Azure' ,
        skillTag: 'azure'
      },
      {
        desc: 'WPF' ,
        skillTag: 'dotnet'
      },
      {
        desc: 'Oracle 11g' ,
        skillTag: 'oracle'
      },
      {
        desc: 'PL/SQL' ,
        skillTag: 'oracle'
      },
      {
        desc: 'Toad for Oracle' ,
        skillTag: 'oracle'
      },
      {
        desc: 'REST',
        skillTag: 'rest'
      }
    ]
  },
  {
    company: 'GROWMARK, Inc.',
    title: 'Contractor',
    location: 'Bloomington, IL',
    startDate: 'Oct 2010',
    endDate: 'Oct 2011',
    achievements: [
      {
        desc: 'Implemented WebNow and ImageNow forms with XML, XSLT, and iScript',
        skillTags:[]
      },
      {
        desc: 'Created image file processors to catalog file metadata on upload',
        skillTags:[]
      }
    ],
    skills: [
      {
        desc: 'C#/F#',
        skillTag: 'dotnet'
      },
      {
        desc: 'ASP.NET 4.0' ,
        skillTag: 'dotnet'
      },
      {
        desc: 'SharePoint 2010' ,
        skillTag: 'sharepoint'
      },
      {
        desc: 'HTML 5' ,
        skillTag: 'web'
      },
      {
        desc: 'JQuery ' ,
        skillTag: 'web'
      },
      {
        desc: 'XML' ,
        skillTag: 'web'
      },
      {
        desc: 'XSLT' ,
        skillTag: 'web'
      },
      {
        desc: 'XSD' ,
        skillTag: 'web'
      }
    ]
  },
  {
    company: 'BAE Systems Inc.',
    title: 'Contractor',
    location: 'Huntsville, AL',
    startDate: 'Dec 2007',
    endDate: 'Oct 2010',
    achievements: [
      {
        desc: 'Implemented SharePoint Features to provision SharePoint sites',
        skillTags:[]
      },
      {
        desc: 'Created customized SharePoint workflows for Contract bidding',
        skillTags:[]
      }
    ],
    skills: [
      {
        desc: 'C#',
        skillTag: 'dotnet'
      },
      {
        desc: 'SharePoint 2007',
        skillTag: 'sharepoint'
      },
      {
        desc: 'ASP.NET 3.5',
        skillTag: 'dotnet'
      },
      {
        desc: 'HTML 4',
        skillTag: 'web'
      },
      {
        desc: 'XML',
        skillTag: 'web'
      },
      {
        desc: 'SOAP',
        skillTag: 'web'
      }
    ]
  }
]
